# This workflow will triage pull requests and apply a label based on the
name: Fabric CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndRunForSomeVersions:
      name: Run tests for ${{ matrix.minecraftVersion }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          minecraftVersion:
            - 1.15.2
            - latest
      steps:
        - uses: actions/checkout@v2
          with:
            lfs: true
        - uses: Geometrically/fabric-test-runner@v1
          id: testRunner
          with:
            minecraftVersion: ${{ matrix.minecraftVersion }}
        - uses: actions/upload-artifact@v1
          with:
            name: Builds
            path: build/libs
